Squashed 'third_party/unordered_dense/' changes from 73f3cbb237..e6dbba2b67
e6dbba2b67 refactor: clean up linter scripts
3b454f0ebe bump version to 4.8.0, update stl.h in linter script
820babe2fc format with clang-format
40a6724ce7 fix example compilation when using modules
349b8c1785 add CI for C++ module on windows-x64/cl and linu-x64x/clang
8ab51b8511 fix stl getting not included on msvc when C++23 is enabled
942bb1d2b6 add support for compiling the example and the module for cmake buildsystem
82bdd82b77 enable C++23 on all CI
48b9d39203 support C++23 import std on unordered_dense module
554c5098b4 Add GitHub Copilot instructions for ankerl::unordered_dense
efd15c4266 Bump version to 4.7.0 with the new replace_key method
73bd97842f Fix typos and improve clarity in README.md
cd32d8e467 Add key replacement and erase-and-shift-down methods to unordered_dense
f8059d8273 Bump version to 4.6.0 in CMakeLists.txt, header file, and Meson build configuration
70a0d5ff1d Refactor CI workflow to enhance MinGW and Windows job configurations, add compiler version printing, and improve artifact handling for test logs.
792f3450ea Enhance Linux sanitizer job to support multiple compilers and update version printing
43d1f4f4a5 Add steps to print compiler versions in CI workflow
cf89359577 Add unit test for segmented_map in array_of_maps.cpp
82c4830527 Fix README.md regarding stability of segmented_map and segmented_set references.
43fa2f36be Refactor type aliasing to remove unnecessary typename qualifiers in unordered_dense.h
c00b36e237 Update CI workflow to also use clang-tidy linter
72ed69de56 Refactor clang-tidy configuration and add linting script for unordered_dense.h
69f59dfeca Add Linux sanitizer job to CI with address, thread, and undefined checks
0d0810ffd4 Enhance CI workflow by adding APT package caching for clang-format and updating linting scripts
9aa4e50d74 Add ARM64 support to Linux CI workflow with compiler matrix
2db8c12ba1 Add MinGW CI job with architecture matrix support, and windows 32bit builds
6fe418a7a1 Enhance Linux CI workflow with compiler and architecture matrix support
651d9eb217 Add C++ version check for likely/unlikely attributes
a3a17f01e8 Add support for c++20 likely/unlikely attributes
0314c5f3ca Fix MinGW build with _WIN32_WINNT<0x600, GCC>=13, model=win32
70c4c79719 Fixed compiler error C2061 in VS2022 syntax error: identifier 'T'"
b4802df020 Disable ubsan's integer sanitizer warnings
f9bd51faca Add tests for segmented_vector resize functionality
5dbcfc7650 implement resize functions
cac780fe97 minor segmented_vector fixes
3553239f15 cache apt
958e572fd4 main.yml: better caching, use latest ccache-action, better permissions
d81bcd37e9 Update github's workflow to latest versions
39f9a06655 Fix compile issues with recent compilers

git-subtree-dir: third_party/unordered_dense
git-subtree-split: e6dbba2b670f5301d415ed2ba8520070a6d33358